server:
  port: ${PORT:8080}
spring:
  application:
    name: Payment_Service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service
    password:
    username: arsen_vaits
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.xml"



jwt:
  secret: "${JWT_SECRET:bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24=}"
  expiration: ${JWT_EXPIRATION:86000}